ACCOUNT_BASE_URL = "https://account-fk.niu.com"
LOGIN_URI = "/v3/api/oauth2/token"
API_BASE_URL = "https://app-api-fk.niu.com"
MOTOR_BATTERY_API_URI = "/v3/motor_data/battery_info"
MOTOR_INDEX_API_URI = "/v5/scooter/motor_data/index_info"
MOTOINFO_LIST_API_URI = "/v5/scooter/list"
MOTOINFO_ALL_API_URI = "/motoinfo/overallTally"
TRACK_LIST_API_URI = "/v5/track/list/v2"
KQI_TRACK_LIST_API_URI = "/v5/k/track_list"
KQI_RIDE_STAT_API_URI = "/v5/car_condition/ride_stat"
KQI_MEDICAL_RECORD_API_URI = "/v5/scooter/medical_record"
KQI_KEY_SHARE_STATISTICS_API_URI = "/v5/scooter/key/share_statistics"
# FIRMWARE_BAS_URL = '/motorota/getfirmwareversion'

DOMAIN = "niu"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_SCOOTER_ID = "scooter_id"
CONF_AUTH = "conf_auth"
CONF_SENSORS = "sensors_selected"

DEFAULT_SCOOTER_ID = 0

SENSOR_TYPE_BAT = "BAT"
SENSOR_TYPE_MOTO = "MOTO"
SENSOR_TYPE_DIST = "DIST"
SENSOR_TYPE_OVERALL = "TOTAL"
SENSOR_TYPE_POS = "POSITION"
# SENSOR_TYPE_SYSTEM = 'SYSTEM'
SENSOR_TYPE_TRACK = "TRACK"
SENSOR_TYPE_RIDESTAT = "RIDESTAT"
SENSOR_TYPE_TRACKSUMMARY = "TRACKSUMMARY"
SENSOR_TYPE_MEDICAL = "MEDICAL"
SENSOR_TYPE_KEYSTATS = "KEYSTATS"

AVAILABLE_SENSORS = [
    "BatteryCharge",
    "Isconnected",
    "TimesCharged",
    "temperatureDesc",
    "Temperature",
    "BatteryGrade",
    "CurrentSpeed",
    "ScooterConnected",
    "IsCharging",
    "IsLocked",
    "TimeLeft",
    "EstimatedMileage",
    "centreCtrlBatt",
    "HDOP",
    "Longitude",
    "Latitude",
    "Distance",
    "RidingTime",
    "totalMileage",
    "DaysInUse",
    "LastTrackStartTime",
    "LastTrackEndTime",
    "LastTrackDistance",
    "LastTrackAverageSpeed",
    "LastTrackRidingtime",
    "LastTrackThumb",
    "KqiMileageThisWeek",
    "KqiMileageTotal",
    "KqiRideCountTotal",
    "KqiRidingMinutesTotal",
    "KqiSharingCostTotal",
    "KqiSharingSavingsTotal",
    "KqiAmortizationPercent",
    "KqiDistanceTotalFromTracks",
    "KqiRideCountThisMonth",
    "KqiRidingMinutesThisMonth",
    "KqiDistanceThisMonth",
    "KqiSharingCostThisMonth",
    "KqiLongestRideDistance",
    "KqiLongestRideDuration",
    "KqiAverageRideDistance",
    "KqiAverageRideDuration",
    "KqiPowerConsumptionTotal",
    "KqiLastRidePowerConsumption",
    "KqiMedicalUseDays",
    "KqiMedicalScore",
    "KqiKeyNfcCount",
    "KqiKeyWalletCount",
    "KqiKeyUserCount",
    "KqiKeyPasswordCount",
]


import voluptuous as vol

from homeassistant.components.sensor import PLATFORM_SCHEMA

# Sensors schemas
from homeassistant.const import CONF_MONITORED_VARIABLES
import homeassistant.helpers.config_validation as cv

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(
    {
        vol.Required(CONF_USERNAME): cv.string,
        vol.Required(CONF_PASSWORD): cv.string,
        vol.Optional(CONF_SCOOTER_ID, default=DEFAULT_SCOOTER_ID): cv.positive_int,
        vol.Optional(CONF_MONITORED_VARIABLES, default=["BatteryCharge"]): vol.All(
            cv.ensure_list,
            vol.Length(min=1),
            [
                vol.In(
                    [
                        "BatteryCharge",
                        "Isconnected",
                        "TimesCharged",
                        "temperatureDesc",
                        "Temperature",
                        "BatteryGrade",
                        "CurrentSpeed",
                        "ScooterConnected",
                        "IsCharging",
                        "IsLocked",
                        "TimeLeft",
                        "EstimatedMileage",
                        "centreCtrlBatt",
                        "HDOP",
                        "Longitude",
                        "Latitude",
                        "Distance",
                        "RidingTime",
                        "totalMileage",
                        "DaysInUse",
                        "LastTrackStartTime",
                        "LastTrackEndTime",
                        "LastTrackDistance",
                        "LastTrackAverageSpeed",
                        "LastTrackRidingtime",
                        "LastTrackThumb",
                        "KqiMileageThisWeek",
                        "KqiMileageTotal",
                        "KqiRideCountTotal",
                        "KqiRidingMinutesTotal",
                        "KqiSharingCostTotal",
                        "KqiSharingSavingsTotal",
                        "KqiAmortizationPercent",
                        "KqiDistanceTotalFromTracks",
                        "KqiRideCountThisMonth",
                        "KqiRidingMinutesThisMonth",
                        "KqiDistanceThisMonth",
                        "KqiSharingCostThisMonth",
                        "KqiLongestRideDistance",
                        "KqiLongestRideDuration",
                        "KqiAverageRideDistance",
                        "KqiAverageRideDuration",
                        "KqiPowerConsumptionTotal",
                        "KqiLastRidePowerConsumption",
                        "KqiMedicalUseDays",
                        "KqiMedicalScore",
                        "KqiKeyNfcCount",
                        "KqiKeyWalletCount",
                        "KqiKeyUserCount",
                        "KqiKeyPasswordCount",
                    ]
                )
            ],
        ),
    }
)

SENSOR_TYPES = {
    "BatteryCharge": [
        "battery_charge",
        "%",
        "batteryCharging",
        SENSOR_TYPE_BAT,
        "battery",
        "mdi:battery-charging-50",
    ],
    "Isconnected": [
        "is_connected",
        "",
        "isConnected",
        SENSOR_TYPE_BAT,
        "connectivity",
        "mdi:connection",
    ],
    "TimesCharged": [
        "times_charged",
        "x",
        "chargedTimes",
        SENSOR_TYPE_BAT,
        "none",
        "mdi:battery-charging-wireless",
    ],
    "temperatureDesc": [
        "temp_descr",
        "",
        "temperatureDesc",
        SENSOR_TYPE_BAT,
        "none",
        "mdi:thermometer-alert",
    ],
    "Temperature": [
        "temperature",
        "°C",
        "temperature",
        SENSOR_TYPE_BAT,
        "temperature",
        "mdi:thermometer",
    ],
    "BatteryGrade": [
        "battery_grade",
        "%",
        "gradeBattery",
        SENSOR_TYPE_BAT,
        "battery",
        "mdi:car-battery",
    ],
    "CurrentSpeed": [
        "current_speed",
        "km/h",
        "nowSpeed",
        SENSOR_TYPE_MOTO,
        "none",
        "mdi:speedometer",
    ],
    "ScooterConnected": [
        "scooter_connected",
        "",
        "isConnected",
        SENSOR_TYPE_MOTO,
        "connectivity",
        "mdi:motorbike-electric",
    ],
    "IsCharging": [
        "is_charging",
        "",
        "isCharging",
        SENSOR_TYPE_MOTO,
        "power",
        "mdi:battery-charging",
    ],
    "IsLocked": ["is_locked", "", "lockStatus", SENSOR_TYPE_MOTO, "lock", "mdi:lock"],
    "TimeLeft": [
        "time_left",
        "h",
        "leftTime",
        SENSOR_TYPE_MOTO,
        "none",
        "mdi:av-timer",
    ],
    "EstimatedMileage": [
        "estimated_mileage",
        "km",
        "estimatedMileage",
        SENSOR_TYPE_MOTO,
        "none",
        "mdi:map-marker-distance",
    ],
    "centreCtrlBatt": [
        "centre_ctrl_batt",
        "%",
        "centreCtrlBattery",
        SENSOR_TYPE_MOTO,
        "battery",
        "mdi:car-cruise-control",
    ],
    "HDOP": ["hdp", "", "hdop", SENSOR_TYPE_MOTO, "none", "mdi:map-marker"],
    "Longitude": ["long", "", "lng", SENSOR_TYPE_POS, "none", "mdi:map-marker"],
    "Latitude": ["lat", "", "lat", SENSOR_TYPE_POS, "none", "mdi:map-marker"],
    "Distance": [
        "distance",
        "m",
        "distance",
        SENSOR_TYPE_DIST,
        "none",
        "mdi:map-marker-distance",
    ],
    "RidingTime": [
        "riding_time",
        "s",
        "ridingTime",
        SENSOR_TYPE_DIST,
        "none",
        "mdi:map-clock",
    ],
    "totalMileage": [
        "total_mileage",
        "km",
        "totalMileage",
        SENSOR_TYPE_OVERALL,
        "none",
        "mdi:map-marker-distance",
    ],
    "DaysInUse": [
        "bind_days_count",
        "days",
        "bindDaysCount",
        SENSOR_TYPE_OVERALL,
        "none",
        "mdi:calendar-today",
    ],
    "LastTrackStartTime": [
        "last_track_start_time",
        "",
        "startTime",
        SENSOR_TYPE_TRACK,
        "none",
        "mdi:clock-start",
    ],
    "LastTrackEndTime": [
        "last_track_end_time",
        "",
        "endTime",
        SENSOR_TYPE_TRACK,
        "none",
        "mdi:clock-end",
    ],
    "LastTrackDistance": [
        "last_track_distance",
        "m",
        "distance",
        SENSOR_TYPE_TRACK,
        "none",
        "mdi:map-marker-distance",
    ],
    "LastTrackAverageSpeed": [
        "last_track_average_speed",
        "km/h",
        "avespeed",
        SENSOR_TYPE_TRACK,
        "none",
        "mdi:speedometer",
    ],
    "LastTrackRidingtime": [
        "last_track_riding_time",
        "",
        "ridingtime",
        SENSOR_TYPE_TRACK,
        "none",
        "mdi:timelapse",
    ],
    "LastTrackThumb": [
        "last_track_thumb",
        "",
        "track_thumb",
        SENSOR_TYPE_TRACK,
        "none",
        "mdi:map",
    ],
    "KqiMileageThisWeek": [
        "kqi_mileage_this_week",
        "m",
        "mileage_this_week",
        SENSOR_TYPE_RIDESTAT,
        "none",
        "mdi:map-marker-distance",
    ],
    "KqiMileageTotal": [
        "kqi_mileage_total",
        "m",
        "mileage_total",
        SENSOR_TYPE_RIDESTAT,
        "none",
        "mdi:map-marker-distance",
    ],
    "KqiRideCountTotal": [
        "kqi_ride_count_total",
        "rides",
        "ride_count_total",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:counter",
    ],
    "KqiRidingMinutesTotal": [
        "kqi_riding_minutes_total",
        "min",
        "riding_minutes_total",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:timer-outline",
    ],
    "KqiSharingCostTotal": [
        "kqi_sharing_cost_total",
        "€",
        "sharing_cost_total",
        SENSOR_TYPE_TRACKSUMMARY,
        "monetary",
        "mdi:cash-multiple",
    ],
    "KqiSharingSavingsTotal": [
        "kqi_sharing_savings_total",
        "€",
        "sharing_savings_total",
        SENSOR_TYPE_TRACKSUMMARY,
        "monetary",
        "mdi:cash-plus",
    ],
    "KqiAmortizationPercent": [
        "kqi_amortization_percent",
        "%",
        "amortization_percent",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:percent-circle",
    ],
    "KqiDistanceTotalFromTracks": [
        "kqi_distance_total_from_tracks",
        "km",
        "distance_total_from_tracks",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:map-marker-distance",
    ],
    "KqiRideCountThisMonth": [
        "kqi_ride_count_this_month",
        "rides",
        "ride_count_this_month",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:calendar-month",
    ],
    "KqiRidingMinutesThisMonth": [
        "kqi_riding_minutes_this_month",
        "min",
        "riding_minutes_this_month",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:timer-outline",
    ],
    "KqiDistanceThisMonth": [
        "kqi_distance_this_month",
        "km",
        "distance_this_month",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:map-marker-distance",
    ],
    "KqiSharingCostThisMonth": [
        "kqi_sharing_cost_this_month",
        "€",
        "sharing_cost_this_month",
        SENSOR_TYPE_TRACKSUMMARY,
        "monetary",
        "mdi:cash-clock",
    ],
    "KqiLongestRideDistance": [
        "kqi_longest_ride_distance",
        "km",
        "longest_ride_distance",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:map-marker-distance",
    ],
    "KqiLongestRideDuration": [
        "kqi_longest_ride_duration",
        "min",
        "longest_ride_duration",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:timer-star-outline",
    ],
    "KqiAverageRideDistance": [
        "kqi_average_ride_distance",
        "km",
        "average_ride_distance",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:chart-bell-curve",
    ],
    "KqiAverageRideDuration": [
        "kqi_average_ride_duration",
        "min",
        "average_ride_duration",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:chart-bell-curve",
    ],
    "KqiPowerConsumptionTotal": [
        "kqi_power_consumption_total",
        "",
        "power_consumption_total",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:flash",
    ],
    "KqiLastRidePowerConsumption": [
        "kqi_last_ride_power_consumption",
        "",
        "last_ride_power_consumption",
        SENSOR_TYPE_TRACKSUMMARY,
        "none",
        "mdi:flash-outline",
    ],
    "KqiMedicalUseDays": [
        "kqi_medical_use_days",
        "days",
        "use_day",
        SENSOR_TYPE_MEDICAL,
        "none",
        "mdi:calendar-check",
    ],
    "KqiMedicalScore": [
        "kqi_medical_score",
        "",
        "score",
        SENSOR_TYPE_MEDICAL,
        "none",
        "mdi:heart-pulse",
    ],
    "KqiKeyNfcCount": [
        "kqi_key_nfc_count",
        "keys",
        "nfc_num",
        SENSOR_TYPE_KEYSTATS,
        "none",
        "mdi:nfc",
    ],
    "KqiKeyWalletCount": [
        "kqi_key_wallet_count",
        "keys",
        "wallet_key_num",
        SENSOR_TYPE_KEYSTATS,
        "none",
        "mdi:wallet",
    ],
    "KqiKeyUserCount": [
        "kqi_key_user_count",
        "users",
        "user_num",
        SENSOR_TYPE_KEYSTATS,
        "none",
        "mdi:account-key",
    ],
    "KqiKeyPasswordCount": [
        "kqi_key_password_count",
        "keys",
        "password_num",
        SENSOR_TYPE_KEYSTATS,
        "none",
        "mdi:form-textbox-password",
    ],
}
